// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	Username string `gorm:"column:username;type:varchar(255)" json:"username"`
	Password string `gorm:"column:password;type:varchar(255)" json:"password"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
